package cn.com.hotled.xyled.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.com.hotled.xyled.bean.LedScreen;
import cn.com.hotled.xyled.bean.Program;
import cn.com.hotled.xyled.bean.TextButton;

import cn.com.hotled.xyled.dao.LedScreenDao;
import cn.com.hotled.xyled.dao.ProgramDao;
import cn.com.hotled.xyled.dao.TextButtonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig ledScreenDaoConfig;
    private final DaoConfig programDaoConfig;
    private final DaoConfig textButtonDaoConfig;

    private final LedScreenDao ledScreenDao;
    private final ProgramDao programDao;
    private final TextButtonDao textButtonDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        ledScreenDaoConfig = daoConfigMap.get(LedScreenDao.class).clone();
        ledScreenDaoConfig.initIdentityScope(type);

        programDaoConfig = daoConfigMap.get(ProgramDao.class).clone();
        programDaoConfig.initIdentityScope(type);

        textButtonDaoConfig = daoConfigMap.get(TextButtonDao.class).clone();
        textButtonDaoConfig.initIdentityScope(type);

        ledScreenDao = new LedScreenDao(ledScreenDaoConfig, this);
        programDao = new ProgramDao(programDaoConfig, this);
        textButtonDao = new TextButtonDao(textButtonDaoConfig, this);

        registerDao(LedScreen.class, ledScreenDao);
        registerDao(Program.class, programDao);
        registerDao(TextButton.class, textButtonDao);
    }
    
    public void clear() {
        ledScreenDaoConfig.clearIdentityScope();
        programDaoConfig.clearIdentityScope();
        textButtonDaoConfig.clearIdentityScope();
    }

    public LedScreenDao getLedScreenDao() {
        return ledScreenDao;
    }

    public ProgramDao getProgramDao() {
        return programDao;
    }

    public TextButtonDao getTextButtonDao() {
        return textButtonDao;
    }

}
