package cn.com.hotled.xyled.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.com.hotled.xyled.bean.Program;
import cn.com.hotled.xyled.bean.TextContent;

import cn.com.hotled.xyled.dao.ProgramDao;
import cn.com.hotled.xyled.dao.TextContentDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig programDaoConfig;
    private final DaoConfig textContentDaoConfig;

    private final ProgramDao programDao;
    private final TextContentDao textContentDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        programDaoConfig = daoConfigMap.get(ProgramDao.class).clone();
        programDaoConfig.initIdentityScope(type);

        textContentDaoConfig = daoConfigMap.get(TextContentDao.class).clone();
        textContentDaoConfig.initIdentityScope(type);

        programDao = new ProgramDao(programDaoConfig, this);
        textContentDao = new TextContentDao(textContentDaoConfig, this);

        registerDao(Program.class, programDao);
        registerDao(TextContent.class, textContentDao);
    }
    
    public void clear() {
        programDaoConfig.clearIdentityScope();
        textContentDaoConfig.clearIdentityScope();
    }

    public ProgramDao getProgramDao() {
        return programDao;
    }

    public TextContentDao getTextContentDao() {
        return textContentDao;
    }

}
